<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/internal/pt/trace_location.proto

namespace BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>internal.pt.CWALocationData</code>
 */
class CWALocationData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>.internal.pt.TraceLocationType type = 2;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>uint32 defaultCheckInLengthInMinutes = 3;</code>
     */
    protected $defaultCheckInLengthInMinutes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type int $type
     *     @type int $defaultCheckInLengthInMinutes
     * }
     */
    public function __construct($data = NULL) {
        \BauerKirch\CoronaWarnAppEventRegistration\Internal\Meta\Pt\TraceLocation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.internal.pt.TraceLocationType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.internal.pt.TraceLocationType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt\TraceLocationType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 defaultCheckInLengthInMinutes = 3;</code>
     * @return int
     */
    public function getDefaultCheckInLengthInMinutes()
    {
        return $this->defaultCheckInLengthInMinutes;
    }

    /**
     * Generated from protobuf field <code>uint32 defaultCheckInLengthInMinutes = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDefaultCheckInLengthInMinutes($var)
    {
        GPBUtil::checkUint32($var);
        $this->defaultCheckInLengthInMinutes = $var;

        return $this;
    }

}

