<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/internal/pt/trace_location.proto

namespace BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>internal.pt.QRCodePayload</code>
 */
class QRCodePayload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>.internal.pt.TraceLocation locationData = 2;</code>
     */
    protected $locationData = null;
    /**
     * Generated from protobuf field <code>.internal.pt.CrowdNotifierData crowdNotifierData = 3;</code>
     */
    protected $crowdNotifierData = null;
    /**
     * byte sequence of CWALocationData
     *
     * Generated from protobuf field <code>bytes vendorData = 4;</code>
     */
    protected $vendorData = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type \BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt\TraceLocation $locationData
     *     @type \BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt\CrowdNotifierData $crowdNotifierData
     *     @type string $vendorData
     *           byte sequence of CWALocationData
     * }
     */
    public function __construct($data = NULL) {
        \BauerKirch\CoronaWarnAppEventRegistration\Internal\Meta\Pt\TraceLocation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.internal.pt.TraceLocation locationData = 2;</code>
     * @return \BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt\TraceLocation|null
     */
    public function getLocationData()
    {
        return isset($this->locationData) ? $this->locationData : null;
    }

    public function hasLocationData()
    {
        return isset($this->locationData);
    }

    public function clearLocationData()
    {
        unset($this->locationData);
    }

    /**
     * Generated from protobuf field <code>.internal.pt.TraceLocation locationData = 2;</code>
     * @param \BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt\TraceLocation $var
     * @return $this
     */
    public function setLocationData($var)
    {
        GPBUtil::checkMessage($var, \BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt\TraceLocation::class);
        $this->locationData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.internal.pt.CrowdNotifierData crowdNotifierData = 3;</code>
     * @return \BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt\CrowdNotifierData|null
     */
    public function getCrowdNotifierData()
    {
        return isset($this->crowdNotifierData) ? $this->crowdNotifierData : null;
    }

    public function hasCrowdNotifierData()
    {
        return isset($this->crowdNotifierData);
    }

    public function clearCrowdNotifierData()
    {
        unset($this->crowdNotifierData);
    }

    /**
     * Generated from protobuf field <code>.internal.pt.CrowdNotifierData crowdNotifierData = 3;</code>
     * @param \BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt\CrowdNotifierData $var
     * @return $this
     */
    public function setCrowdNotifierData($var)
    {
        GPBUtil::checkMessage($var, \BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt\CrowdNotifierData::class);
        $this->crowdNotifierData = $var;

        return $this;
    }

    /**
     * byte sequence of CWALocationData
     *
     * Generated from protobuf field <code>bytes vendorData = 4;</code>
     * @return string
     */
    public function getVendorData()
    {
        return $this->vendorData;
    }

    /**
     * byte sequence of CWALocationData
     *
     * Generated from protobuf field <code>bytes vendorData = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setVendorData($var)
    {
        GPBUtil::checkString($var, False);
        $this->vendorData = $var;

        return $this;
    }

}

