<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/internal/pt/trace_location.proto

namespace BauerKirch\CoronaWarnAppEventRegistration\Internal\Pt;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>internal.pt.TraceLocation</code>
 */
class TraceLocation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     */
    protected $version = 0;
    /**
     * max. 100 characters
     *
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * max. 100 characters
     *
     * Generated from protobuf field <code>string address = 3;</code>
     */
    protected $address = '';
    /**
     * UNIX timestamp (in seconds)
     *
     * Generated from protobuf field <code>uint64 startTimestamp = 5;</code>
     */
    protected $startTimestamp = 0;
    /**
     * UNIX timestamp (in seconds)
     *
     * Generated from protobuf field <code>uint64 endTimestamp = 6;</code>
     */
    protected $endTimestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type string $description
     *           max. 100 characters
     *     @type string $address
     *           max. 100 characters
     *     @type int|string $startTimestamp
     *           UNIX timestamp (in seconds)
     *     @type int|string $endTimestamp
     *           UNIX timestamp (in seconds)
     * }
     */
    public function __construct($data = NULL) {
        \BauerKirch\CoronaWarnAppEventRegistration\Internal\Meta\Pt\TraceLocation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * max. 100 characters
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * max. 100 characters
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * max. 100 characters
     *
     * Generated from protobuf field <code>string address = 3;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * max. 100 characters
     *
     * Generated from protobuf field <code>string address = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * UNIX timestamp (in seconds)
     *
     * Generated from protobuf field <code>uint64 startTimestamp = 5;</code>
     * @return int|string
     */
    public function getStartTimestamp()
    {
        return $this->startTimestamp;
    }

    /**
     * UNIX timestamp (in seconds)
     *
     * Generated from protobuf field <code>uint64 startTimestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->startTimestamp = $var;

        return $this;
    }

    /**
     * UNIX timestamp (in seconds)
     *
     * Generated from protobuf field <code>uint64 endTimestamp = 6;</code>
     * @return int|string
     */
    public function getEndTimestamp()
    {
        return $this->endTimestamp;
    }

    /**
     * UNIX timestamp (in seconds)
     *
     * Generated from protobuf field <code>uint64 endTimestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->endTimestamp = $var;

        return $this;
    }

}

